#!/usr/bin/env bash
# Script that display information about domain
if [ $# == 1 ]; then
domain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
domain=$2.$1
fi
dig "$domain" | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print "The subbdomain", b[1], "is a", $4, "record and point to", $5}'
