#!/usr/bin/env bash
# installs nginx and configures it on a remote server

add_redirction="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

apt-get -y update
apt-get -y install nginx
sudo touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "30i $add_redirction" /etc/nginx/sites-available/default
service nginx restart
