#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sed i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com@cryptotechcoder parmanent;' /ect/nginx/sites_available/default
service nginx restart
