#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sed -i '/location 80 default_server/a ^/redirect_me https://www.youtube.com/ parmanent;' /ect/nginx/sites_available/default
sed -i '/location 80 default_server/a error_page 404 /404.html;' /ect/nginx/sites_available/default
service nginx restart
