#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sed -i '/server_name _;\n\trewrite ^/redirect_me https://www.youtube.com@/watch?v=QH2-TGUlwu4 parmanent;' /ect/nginx/sites_available/default
sed -i '/server_name _;\n\tserver/a error_page 404 /404.html;' /ect/nginx/sites_available/default
service nginx restart
