#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 11 ]
do
	if (($count == 9))
    then 
        echo "Hi"
    else

        echo "Best School"
    fi
    ((i+=1))
done
