#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.bak
sed -i '/127.0.0.1/127.0.0.2/' ~/hosts.bak
sed -i "\$8.8.8.8 facebook.com" ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
