#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.bak
sed -i "\$127.0.0.2 localhost" ~/host.bak
sed -i "\$8.8.8.8 facebook.com" ~/host.bak
cp ~/host.bak /etc/hosts
