#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
sudo cp /etc/hosts /etc/hosts.bak

# Edit the hosts file
sudo sed -i '/localhost/ s/.*/127.0.0.2\tlocalhost/' /etc/hosts
sudo sed -i '/facebook.com/ s/.*/8.8.8.8\tfacebook.com/' /etc/hosts
